CREATE DATABASE nube;

USE nube;


/*images table*/
CREATE TABLE images(
id INT(11) NOT NULL AUTO_INCREMENT,
filename VARCHAR(255) NOT NULL,
upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);


/*video table*/
CREATE TABLE video(
id INT(11) NOT NULL AUTO_INCREMENT,
filename VARCHAR(255) NOT NULL,
upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);


/*audio table*/
CREATE TABLE audio(
id INT(11) NOT NULL AUTO_INCREMENT,
filename VARCHAR(255) NOT NULL,
upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);


/*document table*/
CREATE TABLE document(
id INT(11) NOT NULL AUTO_INCREMENT,
filename VARCHAR(255) NOT NULL,
upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);